importar_base_dados:-
    retractall(membro(_,_,_)),
    retractall(meio_transporte(_,_,_,_)),
    retractall(equipamento(_,_)),
    retractall(ligacao(_,_,_,_,_,_,_)),
    assert(membro(hospital,lusiadas,faro)),
    assert(membro(clinica,aqualab,faro)),
    assert(membro(armazem,'alcool corp',beja)),
    assert(membro(clinica,'beja clinic',beja)),
    assert(membro(hospital,'garcia da orta',setubal)),
    assert(membro(hospital,'cuf caparica',setubal)),
    assert(membro(hospital,'cuf evora',evora)),
    assert(membro(armazem,'mascaras lda',evora)),
    assert(membro(clinica,luz,lisboa)),
    assert(membro(clinica,alvalade,lisboa)),
    assert(membro(armazem,'viseiras lda',portalegre)),
    assert(membro(armazem,'ventiladores lda',santarem)),
    assert(membro(clinica,'luis lourenco',leiria)),
    assert(membro(armazem,'luvas lda','castelo branco')),
    assert(membro(hospital,'centro hospitalar universitario',coimbra)),
    assert(membro(clinica,'martins de sousa',guarda)),
    assert(membro(hospital,'santa maria',aveiro)),
    assert(membro(armazem,'protecao lda',viseu)),
    assert(membro(hospital,'cuf porto',porto)),
    assert(membro(armazem,'alcool gel lda',braganca)),
    assert(membro(clinica,'joao reis','vila real')),
    assert(membro(hospital,'cuf braga',braga)),
    assert(membro(clinica,'castelo clinic','viana do castelo')),

    assert(meio_transporte(carro,80,'08:00','20:00')),
    assert(meio_transporte(carrinha,70,'01:00','12:00')),
    assert(meio_transporte(comboio,120,'05:00','17:00')),
    assert(meio_transporte(helicopetro,250,'12:00','18:00')),

    assert(equipamento(ventilador,lusiadas)),
    assert(equipamento(luvas,aqualab)),
    assert(equipamento(alcool,'alcool corp')),
    assert(equipamento(mascara,'beja clinic')),
    assert(equipamento(viseira,'garcia da orta')),
    assert(equipamento(bata,'cuf caparica')),
    assert(equipamento(oculos,'cuf evora')),
    assert(equipamento(mascara,'mascaras lda')),
    assert(equipamento(touca,luz)),
    assert(equipamento(cogula,alvalade)),
    assert(equipamento(viseira,'viseiras lda')),
    assert(equipamento(ventilador,'ventiladores lda')),
    assert(equipamento(zaragatoa,'luis lourenco')),
    assert(equipamento(luvas,'luvas lda')),
    assert(equipamento('alcool gel','centro hospitalar universitario')),
    assert(equipamento('protecao de calcado','martins de sousa')),
    assert(equipamento(manguitos,'santa maria')),
    assert(equipamento('mascara cirurgica','protecao lda')),
    assert(equipamento('bata cirurgica','cuf porto')),
    assert(equipamento(alcool,'alcool gel lda')),
    assert(equipamento(mascara,'joao reis')),
    assert(equipamento(viseira,'cuf braga')),
    assert(equipamento(cogula,'castelo clinic')),

    assert(ligacao(aqualab,lusiadas,80,carrinha,'01:00','12:00',luvas)),
    assert(ligacao(aqualab,'beja clinic',80,carrinha,'01:00','12:00',luvas)),
    assert(ligacao('beja clinic','alcool corp',50,carro,'08:00','20:00',mascara)),
    assert(ligacao('alcool corp','cuf evora',50,carro,'08:00','20:00',alcool)),
    assert(ligacao('cuf evora','mascaras lda',30,carrinha,'01:00','12:00',oculos)),
    assert(ligacao('mascaras lda','viseiras lda',60,carrinha,'01:00','12:00',mascara)),
    assert(ligacao(lusiadas,'cuf caparica',100,carrinha,'01:00','12:00',ventilador)),
    assert(ligacao('cuf caparica','garcia da orta',40,carrinha,'01:00','12:00',bata)),
    assert(ligacao('garcia da orta','cuf evora',50,carrinha,'01:00','12:00',viseira)),
    assert(ligacao('garcia da orta',luz,60,carro,'08:00','20:00',viseira)),
    assert(ligacao('garcia da orta',alvalade,30,carro,'08:00','20:00',viseira)),
    assert(ligacao(luz,alvalade,20,carro,'08:00','20:00',touca)),
    assert(ligacao(alvalade,'ventiladores lda',40,carrinha,'01:00','12:00',cogula)),
    assert(ligacao('viseiras lda','ventiladores lda',50,comboio,'05:00','17:00',viseira)),
    assert(ligacao('viseiras lda','luvas lda',120,comboio,'05:00','17:00',viseira)),
    assert(ligacao('ventiladores lda','luis lourenco',20,carrinha,'01:00','12:00',ventilador)),
    assert(ligacao('ventiladores lda','protecao lda',220,comboio,'05:00','17:00',ventilador)),
    assert(ligacao('luis lourenco','centro hospitalar universitario',40,carrinha,'01:00','12:00',zaragatoa)),
    assert(ligacao('centro hospitalar universitario','santa maria',40,carrinha,'01:00','12:00','alcool gel')),
    assert(ligacao('santa maria','cuf porto',25,carro,'08:00','20:00',manguitos)),
    assert(ligacao('protecao lda','cuf porto',80,carrinha,'01:00','12:00','mascara cirurgica')),
    assert(ligacao('luvas lda', 'protecao lda',120,comboio,'05:00','17:00',luvas)),
    assert(ligacao('cuf porto','castelo clinic',70,carro,'08:00','20:00','bata cirurgica')),
    assert(ligacao('protecao lda','joao reis',80,comboio,'05:00','17:00','mascara cirurgica')),
    assert(ligacao('joao reis','cuf braga',50,carro,'08:00','20:00',mascara)),
    assert(ligacao('cuf braga','castelo clinic',40,carro,'08:00','20:00',viseira)),
    assert(ligacao('luvas lda','alcool gel lda',150, helicopetro,'12:00','18:00',luvas)),
    assert(ligacao('luvas lda','martins de sousa',50,comboio,'05:00','17:00',luvas)),
    assert(ligacao('martins de sousa','alcool gel lda',50,comboio,'05:00','17:00','protecao de calcado')),
    assert(ligacao('protecao lda','alcool gel lda',120,comboio,'05:00','17:00','mascara cirurgica')),
    write('Base de dados importada com sucesso.\n\n').

eliminar_base_dados:-
    retractall(membro(_,_,_)),
    retractall(meio_transporte(_,_,_,_)),
    retractall(equipamento(_,_)),
    retractall(ligacao(_,_,_,_,_,_,_)),
    write('Base de dados eliminada com sucesso.\n\n').

